# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: chat_app
  host: localhost
  username: root
  password: root
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: chat_app
  pool: 5
  username:
  password: